
#Область include_core_vo2_СпособыОбмена_ExtSDK_2_WriteDocumentEx
#КонецОбласти 

#Область include_core_vo2_СпособыОбмена_ExtSDK_2_ExecuteActionEx  
#КонецОбласти

#Область include_core_vo2_СпособыОбмена_ExtSDK_2_СобытияОтправки
#КонецОбласти

#Область include_core_vo2_СпособыОбмена_ExtSDK_2_АсинхронныеОтветы
#КонецОбласти

