
#Область include_core2_base_Helpers_ExtException
#КонецОбласти

#Область include_core2_vo2_МодульОбъекта_КлиентСервер_Классы_ПрикладнойОбъект
#КонецОбласти

#Область include_core_base_Классы_ОбъектSABY_ОбъектSABY
#КонецОбласти

